name: Notesync

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notesync
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Change a folder because a Python module name can't have dashes
          path: notesync
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          # Cache pip dependencies
          cache: 'pip'
      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgl1-mesa-dev
          version: 1.0
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest
